### ISSUE TITLE
Increase readings sensitivity

### ISSUE THREAD

**Issue by mdelag** [alextaujenis/RBD_WaterSensor#1]
Hi, is there a way to increase steps in reading values? My problem is that I want to measure very fine changes in the water level but the reading values does not seem to change.

**Comment by alextaujenis** [comment]
Consider using multiple instances of this library and multiple sensors. You can detect very small changes in water level by running horizontal strips of aluminum (not vertical like the example in the docs). Run 4 or 5 horizontal strips (or however many you need) at the pre-defined water levels and when each sensor is triggered - you know the water level at very fine increments. You will need to attach each sensor to 2 pins, and include another resistor.
