### ISSUE TITLE
Invalid library 

### ISSUE THREAD

**Issue by dharveymi** [alextaujenis/RBD_WaterSensor#2]
Arduino make/model Arduino Uno R3
IDE version: 1.8.3
Invalid library found in C:\Program Files (x86)\Arduino\libraries\WaterSensor: C:\Program Files (x86)\Arduino\libraries\WaterSensor

on build:
C:\Users\dharv\Desktop\calibrate_water_sensor\calibrate_water_sensor.ino:7:78: fatal error: RBD_Threshold.h: No such file or directory

**Comment by alextaujenis** [comment]
The `RBD::Threshold` and `RBD::Capacitance` libraries are required to use the `RBD::WaterSensor` library. 

Install the `RBD::Threshold` and `RBD::Capacitance` library from your Arduino IDE:

1. Click **Sketch** in the top menu
1. Click **Include Library** 
1. Click **Manage Libraries**
1. Type `RBD` into the search bar
1. Click **Install** on `RBD::Threshold` and `RBD::Capacitance`
